HOST = "127.0.0.1"
PORT = 8000
MODE = "development"
ASSETS_PATH = "./web/assets"
DATA_PATH = "/Users/hongli/Workspace/NAME/bin/data"
UPLOADS_PATH = "/uploads"

[database]
DRIVER = "sqlite"
DATA_PATH = "."
FILE_NAME = "name.db"
HOST = "localhost"
PORT = "5432"
NAME = "name"
USER = "postgres"
PASSWORD = "your_new_secure_password_here"
SSL_MODE = "disable"
TIME_ZONE = "Asia/Shanghai"

[jwt]
ACCESS_TOKEN_MAX_AGE = 3600
REFRESH_TOKEN_MAX_AGE = 86400
ISSUER = "NAME"
SECRET_KEY = "replace me"