ROOT_URL = "http://localhost"
PORT = 8000
MODE = "development"
STATIC_PATH = "/static"
API_VERSION= "1.0"

[database]
HOST = "127.0.0.1:5432"
NAME = "name"
USER = "postgres"
PASSWORD = "postgres"

[jwt]
SECRET_KEY = "replace this"
ACCESS_TOKEN_MAX_AGE = 1
REFRESH_TOKEN_MAX_AGE = 2

