definitions:
  iris.Map:
    additionalProperties: true
    type: object
  model.PostRequest:
    properties:
      abstract:
        type: string
      allowComment:
        type: boolean
      authorID:
        type: integer
      id:
        type: integer
      isPublic:
        type: boolean
      text:
        type: string
      title:
        type: string
    type: object
  model.Response:
    properties:
      data:
        $ref: '#/definitions/iris.Map'
      message:
        default: message string
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: me@seahi.me
    name: API Support
    url: http://www.swagger.io/support
  description: This is a distributed blog server.
  title: NAME API
  version: "1.0"
paths:
  /api/v1/posts:
    get:
      consumes:
      - application/json
      description: Get posts list
      parameters:
      - description: Access token with the prefix `Bearer `
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1
        description: page size
        in: query
        name: pageSize
        required: true
        type: integer
      - default: 1
        description: page index
        in: query
        name: pageIndex
        required: true
        type: integer
      - default: '"created_at desc"'
        description: order
        in: query
        name: orderBy
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/model.Response'
      summary: Get posts list
    post:
      consumes:
      - application/json
      description: Create a new post
      parameters:
      - description: Access token with the prefix `Bearer `
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/model.PostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - ApiKeyAuth: []
      - OAuth2Implicit:
        - admin
        - write
      summary: Create a new post
swagger: "2.0"
